# application-local.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: orderuser
    password: orderpassword
  kafka:
    bootstrap-servers: localhost:9092

payment:
  service:
    url: http://localhost:8081